// Centralized nav item config for all roles
export const NAV_ITEMS = {
  landing: [
    { label: "Home", href: "/" },
    { label: "Jobs", href: "/jobs" },
    { label: "Browse Talent", href: "/talent" },
    { label: "Recruiters", href: "/recruiters" },
    { label: "Insights", href: "/insights" },
    { label: "Interview Prep", href: "/resources/interview-prep" },
    { label: "Resume Tips", href: "/resources/resume-tips" },
    { label: "Resume Template", href: "/resources/resume-template" },
    { label: "How it Works", href: "/how-it-works" },
    { label: "About", href: "/about" },
    { label: "Contact", href: "/contact" },
    { label: "Help", href: "/help" },
    { label: "Legal", href: "/terms" },
    { label: "Apply for Job", href: "/apply-job" },
  ],
  candidate: [
    { label: "Home", href: "/" },
    { label: "Browse Jobs", href: "/jobs" },
    { label: "Saved Jobs", href: "/saved-jobs" },
    { label: "Messages", href: "/messages" },
    { label: "Profile", href: "/my-profile" },
    { label: "Settings", href: "/settings" },
    { label: "Help", href: "/help" },
  ],
  recruiter: [
    { label: "Dashboard", href: "/recruiter/dashboard" },
    { label: "Post Job", href: "/recruiter/dashboard/post-job" },
    { label: "My Jobs", href: "/recruiter/dashboard/my-jobs" },
    { label: "Applications", href: "/recruiter/dashboard/applications" },
    { label: "Messages", href: "/recruiter/dashboard/messages" },
    { label: "Company Profile", href: "/recruiter/company-profile" },
    { label: "Settings", href: "/settings" },
    { label: "Help", href: "/help" },
  ],
  admin: [
    { label: "Admin Dashboard", href: "/admin/dashboard" },
    { label: "User Management", href: "/admin/dashboard/user-management" },
    { label: "Job Management", href: "/admin/dashboard/job-management" },
    { label: "Reports", href: "/admin/dashboard/reports" },
    { label: "Settings", href: "/settings" },
  ],
};
